'use client';

import { useState, useEffect, useMemo } from 'react';
import type { InvoiceProcessingResult } from '@/lib/types';
import {
  buildTrendData, topVendors, topItems,
  daysUntilDue, dueDateStatus, nlSearch,
  buildDailyReportData,
} from '@/lib/invoice-intelligence';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid,
} from 'recharts';
import {
  ShieldCheck, ShieldAlert, FileText, TrendingUp,
  AlertTriangle, BadgeCheck, Search, CalendarClock,
  Package, Users, Download, Camera, Upload, Plus,
} from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';

interface DashboardViewProps {
  history: InvoiceProcessingResult[];
  onUploadClick: () => void;
  onCameraClick: () => void;
  onNewInvoiceClick?: () => void;
  isOnline?: boolean;
  offlineQueueCount?: number;
}

function exportDailyReport(history: InvoiceProcessingResult[]) {
  const report = buildDailyReportData(history);
  const fmt = (n: number) => n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const rows = report.invoices.map(inv => `
    <tr style="border-bottom:1px solid #eee">
      <td style="padding:8px">${inv.validatedData.customer_name || 'Unknown'}</td>
      <td style="padding:8px">${inv.validatedData.invoice_number || '—'}</td>
      <td style="padding:8px">${inv.validatedData.category || '—'}</td>
      <td style="padding:8px;text-align:right;font-weight:bold">${fmt(inv.validatedData.total || 0)}</td>
      <td style="padding:8px;text-align:center;color:${inv.status === 'approved' ? '#16a34a' : inv.status === 'error' ? '#dc2626' : inv.status === 'rejected' ? '#6b7280' : '#d97706'};font-weight:bold">${inv.status.toUpperCase()}</td>
      <td style="padding:8px;text-align:center">${inv.healthScore ?? '—'}/100</td>
    </tr>`).join('');
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>InvoiceGuard Daily Report — ${report.date}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;padding:20px;color:#111;max-width:900px;margin:0 auto}h1{color:#0d9488;font-size:24px}table{width:100%;border-collapse:collapse;margin-top:16px}th{background:#f3f4f6;padding:10px 8px;text-align:left;font-size:13px}td{font-size:13px}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin:16px 0}.stat{background:#f9fafb;border-radius:8px;padding:12px;text-align:center}.sv{font-size:26px;font-weight:900}.sl{font-size:11px;color:#666;margin-top:2px}hr{margin:16px 0;border:none;border-top:1px solid #e5e7eb}@media(max-width:600px){table{font-size:11px}th,td{padding:6px 4px}.sv{font-size:20px}}</style>
  </head><body>
  <h1>🛡️ InvoiceGuard AI — Daily Report</h1>
  <p style="color:#666;font-size:14px">${report.date} | Generated by InvoiceGuard AI for field salesmen</p>
  <hr>
  <div class="stats">
    <div class="stat"><div class="sv">${report.totalInvoices}</div><div class="sl">Invoices Scanned</div></div>
    <div class="stat"><div class="sv">${fmt(report.totalValue)}</div><div class="sl">Total Value</div></div>
    <div class="stat"><div class="sv" style="color:${report.moneyAtRisk > 0 ? '#dc2626' : '#16a34a'}">${fmt(report.moneyAtRisk)}</div><div class="sl">Money At Risk</div></div>
    <div class="stat"><div class="sv" style="color:#16a34a">${fmt(report.moneySafe)}</div><div class="sl">Approved Safe</div></div>
    <div class="stat"><div class="sv" style="color:${report.errorCount > 0 ? '#dc2626' : '#16a34a'}">${report.errorCount}</div><div class="sl">Error Invoices</div></div>
  </div>
  <hr>
  <table><thead><tr><th>Customer</th><th>Invoice #</th><th>Category</th><th>Total</th><th>Status</th><th>Health</th></tr></thead>
  <tbody>${rows}</tbody></table>
  <hr>
  ${report.moneyAtRisk > 0
    ? `<p style="color:#dc2626;font-weight:bold;font-size:15px">⚠️ ACTION REQUIRED: ${fmt(report.moneyAtRisk)} is on invoices with errors. Do NOT release these payments until corrected.</p>`
    : `<p style="color:#16a34a;font-weight:bold;font-size:15px">✅ All invoices verified. No money at risk today.</p>`}
  </body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `InvoiceGuard_${report.date.replace(/\//g, '-')}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export const DashboardView = ({
  history, onUploadClick, onCameraClick, onNewInvoiceClick, isOnline = true, offlineQueueCount = 0,
}: DashboardViewProps) => {
  const [isClient, setIsClient] = useState(false);
  const [nlQuery, setNlQuery] = useState('');
  const [trendMode, setTrendMode] = useState<'weekly' | 'monthly'>('monthly');

  useEffect(() => { setIsClient(true); }, []);

  const metrics = useMemo(() => history.reduce((acc, item) => {
    const total = item.validatedData.total || 0;
    acc.totalValue += total;
    acc.count++;
    if (item.status === 'verified' || item.status === 'corrected') acc.clean++;
    if (item.status === 'error') { acc.errors++; acc.atRisk += total; }
    if (item.status === 'approved') acc.approved++;
    if (item.status === 'rejected') acc.rejected++;
    if (item.isDuplicate) acc.duplicates++;
    const cat = item.validatedData.category || 'Uncategorized';
    acc.byCategory[cat] = (acc.byCategory[cat] || 0) + total;
    return acc;
  }, { totalValue: 0, count: 0, clean: 0, errors: 0, atRisk: 0, approved: 0, rejected: 0, duplicates: 0, byCategory: {} as Record<string, number> }), [history]);

  const cleanRate = metrics.count > 0 ? Math.round(((metrics.clean + metrics.approved) / metrics.count) * 100) : 100;
  const overdueInvoices = useMemo(() => history.filter(inv => dueDateStatus(daysUntilDue(inv.dueDate)) === 'overdue'), [history]);
  const dueSoonInvoices = useMemo(() => history.filter(inv => dueDateStatus(daysUntilDue(inv.dueDate)) === 'due-soon'), [history]);
  const searchResults = useMemo(() => nlQuery.trim().length > 1 ? nlSearch(nlQuery, history) : null, [nlQuery, history]);
  const trendData = useMemo(() => buildTrendData(history, trendMode), [history, trendMode]);
  const vendorData = useMemo(() => topVendors(history, 5), [history]);
  const itemData = useMemo(() => topItems(history, 5), [history]);
  const categoryData = Object.entries(metrics.byCategory).map(([name, amount]) => ({ name, amount })).sort((a, b) => b.amount - a.amount);

  const fmt = (n: number) => n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  return (
    <div className="w-full space-y-4 animate-fade-in-up">

      {/* Page title */}
      <div className="flex items-center justify-between gap-3">
        <div>
          <h2 className="text-2xl font-bold">Dashboard</h2>
          <p className="text-muted-foreground text-sm">Every scan protects your money</p>
        </div>
        {onNewInvoiceClick && (
          <button
            onClick={onNewInvoiceClick}
            className="flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-violet-500 hover:bg-violet-600 active:scale-95 text-white font-bold text-sm flex-shrink-0 transition-colors"
          >
            <Plus className="h-4 w-4" />
            New Invoice
          </button>
        )}
      </div>

      {/* ── OFFLINE BANNER ── */}
      {!isOnline && (
        <div className="rounded-2xl bg-yellow-50 dark:bg-yellow-900/30 border-2 border-yellow-300 p-4 flex items-center gap-3">
          <span className="text-2xl">📵</span>
          <div>
            <p className="font-bold text-yellow-800 dark:text-yellow-300">You are offline</p>
            <p className="text-sm text-yellow-700 dark:text-yellow-400">{offlineQueueCount > 0 ? `${offlineQueueCount} invoice(s) queued — will process when reconnected` : 'Scanned invoices will be queued for when you reconnect'}</p>
          </div>
        </div>
      )}

      {/* ── OVERDUE / DUE SOON ALERTS ── */}
      {isClient && overdueInvoices.length > 0 && (
        <div className="rounded-2xl bg-red-50 dark:bg-red-950/40 border-2 border-red-400 p-4 flex items-start gap-3">
          <AlertTriangle className="h-6 w-6 text-red-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-red-700 dark:text-red-400 text-base">
              {overdueInvoices.length} Invoice{overdueInvoices.length > 1 ? 's' : ''} OVERDUE
            </p>
            <p className="text-sm text-red-600 dark:text-red-300 mt-1">
              {overdueInvoices.map(i => i.validatedData.customer_name || 'Unknown').join(' · ')}
            </p>
          </div>
        </div>
      )}
      {isClient && dueSoonInvoices.length > 0 && (
        <div className="rounded-2xl bg-orange-50 dark:bg-orange-950/40 border-2 border-orange-300 p-4 flex items-start gap-3">
          <CalendarClock className="h-6 w-6 text-orange-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-orange-700 dark:text-orange-400 text-base">
              {dueSoonInvoices.length} Due Within 3 Days
            </p>
            <p className="text-sm text-orange-600 dark:text-orange-300 mt-1">
              {dueSoonInvoices.map(i => i.validatedData.customer_name || 'Unknown').join(' · ')}
            </p>
          </div>
        </div>
      )}

      {/* ── EMPTY STATE — hero scan prompt ── */}
      {isClient && metrics.count === 0 && (
        <div className="rounded-2xl border-2 border-dashed border-primary/40 bg-primary/5 p-8 text-center space-y-4">
          <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
            <FileText className="h-10 w-10 text-primary" />
          </div>
          <div>
            <p className="text-xl font-bold">Ready to scan</p>
            <p className="text-muted-foreground text-sm mt-1">Photograph or upload a customer invoice to verify it instantly</p>
          </div>
          <div className="flex flex-col gap-3 pt-2">
            <button className="action-btn-primary" onClick={onCameraClick}>
              <Camera className="h-6 w-6" /> Scan Invoice with Camera
            </button>
            <button className="action-btn-secondary" onClick={onUploadClick}>
              <Upload className="h-5 w-5" /> Upload from Phone
            </button>
          </div>
        </div>
      )}

      {/* ── 4 KEY METRIC CARDS ── */}
      {isClient && metrics.count > 0 && (
        <div className="grid grid-cols-2 gap-3">
          {/* Total value */}
          <Card className="rounded-2xl">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-1">
                <TrendingUp className="h-4 w-4 text-primary" />
                <span className="text-xs text-muted-foreground font-medium">Total Value</span>
              </div>
              <div className="text-2xl font-black leading-tight break-all">{fmt(metrics.totalValue)}</div>
              <p className="text-xs text-muted-foreground mt-1">{metrics.count} invoice{metrics.count !== 1 ? 's' : ''}</p>
            </CardContent>
          </Card>

          {/* Money at risk */}
          <Card className={`rounded-2xl ${metrics.atRisk > 0 ? 'border-2 border-red-400 bg-red-50/50 dark:bg-red-950/20' : 'border-2 border-green-300 bg-green-50/50 dark:bg-green-950/20'}`}>
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-1">
                <ShieldAlert className={`h-4 w-4 ${metrics.atRisk > 0 ? 'text-red-600' : 'text-green-600'}`} />
                <span className="text-xs text-muted-foreground font-medium">At Risk</span>
              </div>
              <div className={`text-2xl font-black leading-tight break-all ${metrics.atRisk > 0 ? 'text-red-600' : 'text-green-600'}`}>
                {fmt(metrics.atRisk)}
              </div>
              <p className="text-xs text-muted-foreground mt-1">{metrics.atRisk > 0 ? `${metrics.errors} error invoice${metrics.errors > 1 ? 's' : ''}` : 'All clear ✓'}</p>
            </CardContent>
          </Card>

          {/* Invoice health */}
          <Card className={`rounded-2xl ${cleanRate === 100 ? 'border-2 border-green-300 bg-green-50/50 dark:bg-green-950/20' : cleanRate < 50 ? 'border-2 border-red-300' : ''}`}>
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-1">
                <ShieldCheck className={`h-4 w-4 ${cleanRate === 100 ? 'text-green-600' : cleanRate < 50 ? 'text-red-600' : 'text-yellow-600'}`} />
                <span className="text-xs text-muted-foreground font-medium">Health</span>
              </div>
              <div className={`text-2xl font-black leading-tight ${cleanRate === 100 ? 'text-green-600' : cleanRate < 50 ? 'text-red-600' : 'text-yellow-600'}`}>
                {cleanRate}%
              </div>
              <p className="text-xs text-muted-foreground mt-1">{metrics.errors} of {metrics.count} had errors</p>
            </CardContent>
          </Card>

          {/* Invoices breakdown */}
          <Card className="rounded-2xl">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-1">
                <FileText className="h-4 w-4 text-primary" />
                <span className="text-xs text-muted-foreground font-medium">Scanned</span>
              </div>
              <div className="text-2xl font-black leading-tight">{metrics.count}</div>
              <div className="flex flex-wrap gap-1 mt-1">
                {metrics.approved > 0 && <span className="text-xs font-bold text-blue-600">{metrics.approved}✓</span>}
                {metrics.errors > 0 && <span className="text-xs font-bold text-red-600">{metrics.errors}✗</span>}
                {metrics.duplicates > 0 && <span className="text-xs font-bold text-orange-600">{metrics.duplicates}⚠</span>}
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* ── END OF DAY SUMMARY ── */}
      {isClient && metrics.count > 0 && (
        <Card className="rounded-2xl border-2 border-primary/30 bg-primary/5">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="flex items-center gap-2 text-base">
              <BadgeCheck className="h-5 w-5 text-primary" /> Today's Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4 space-y-2">
            <p className="text-sm">Scanned <strong>{metrics.count}</strong> invoice{metrics.count !== 1 ? 's' : ''} · Total value <strong>{fmt(metrics.totalValue)}</strong></p>
            {metrics.atRisk > 0 ? (
              <div className="rounded-xl bg-red-100 dark:bg-red-900/30 border border-red-300 p-3 flex items-start gap-2">
                <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                <p className="text-sm font-semibold text-red-700 dark:text-red-300">
                  ⚠️ {fmt(metrics.atRisk)} on {metrics.errors} error invoice{metrics.errors > 1 ? 's' : ''} — do NOT accept payment until corrected
                </p>
              </div>
            ) : (
              <p className="text-sm font-semibold text-green-700 dark:text-green-400">✅ All invoices verified — you are protected today</p>
            )}
            {metrics.duplicates > 0 && (
              <p className="text-sm font-bold text-orange-700 dark:text-orange-400">🔴 {metrics.duplicates} duplicate invoice{metrics.duplicates > 1 ? 's' : ''} — do NOT collect twice</p>
            )}
            {/* Daily report download */}
            <button
              className="action-btn-secondary mt-2 !min-h-[48px]"
              onClick={() => exportDailyReport(history)}
            >
              <Download className="h-5 w-5" /> Download Daily Report
            </button>
          </CardContent>
        </Card>
      )}

      {/* ── NATURAL LANGUAGE SEARCH ── */}
      {isClient && history.length > 0 && (
        <div className="space-y-2">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
            <Input
              className="pl-11 h-14 text-base rounded-2xl"
              placeholder='Search: "errors", "over 5000", "Groceries"...'
              value={nlQuery}
              onChange={e => setNlQuery(e.target.value)}
            />
          </div>
          {searchResults !== null && (
            <p className="text-sm text-muted-foreground px-1">
              {searchResults.length} result{searchResults.length !== 1 ? 's' : ''}
              {searchResults.length > 0 && <span> — total <strong>{fmt(searchResults.reduce((s, i) => s + (i.validatedData.total || 0), 0))}</strong></span>}
            </p>
          )}
        </div>
      )}

      {/* ── TREND CHART ── */}
      {isClient && trendData.length > 0 && (
        <Card className="rounded-2xl">
          <CardHeader className="px-4 pt-4 pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">Spending Trend</CardTitle>
              <div className="flex gap-1">
                <button
                  className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-colors ${trendMode === 'monthly' ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}
                  onClick={() => setTrendMode('monthly')}
                >Monthly</button>
                <button
                  className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-colors ${trendMode === 'weekly' ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}
                  onClick={() => setTrendMode('weekly')}
                >Weekly</button>
              </div>
            </div>
          </CardHeader>
          <CardContent className="px-2 pb-4">
            <div style={{ width: '100%', height: 200 }}>
              <ResponsiveContainer>
                <LineChart data={trendData} margin={{ top: 5, right: 10, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                  <XAxis dataKey="label" tick={{ fontSize: 10 }} />
                  <YAxis tickFormatter={v => v >= 1000 ? `${(v / 1000).toFixed(0)}k` : v} tick={{ fontSize: 10 }} />
                  <Tooltip formatter={(v: number) => fmt(v)} contentStyle={{ background: 'hsl(var(--background))', border: '1px solid hsl(var(--border))', borderRadius: 12, fontSize: 12 }} />
                  <Line type="monotone" dataKey="amount" name="Value" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={false} />
                  <Line type="monotone" dataKey="errors" name="Errors" stroke="#ef4444" strokeWidth={1.5} strokeDasharray="4 2" dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── ANALYTICS: Vendors + Items + Categories ── */}
      {isClient && metrics.count > 0 && (
        <div className="space-y-3">
          {/* Top customers */}
          <Card className="rounded-2xl">
            <CardHeader className="px-4 pt-4 pb-2">
              <CardTitle className="text-base flex items-center gap-2"><Users className="h-4 w-4 text-primary" /> Top Customers</CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4 space-y-3">
              {vendorData.length === 0 ? <p className="text-sm text-muted-foreground">No data</p> : vendorData.map((v, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center flex-shrink-0">{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold truncate">{v.name}</p>
                    <p className="text-xs text-muted-foreground">{v.count} invoice{v.count > 1 ? 's' : ''}</p>
                  </div>
                  <span className="text-sm font-bold flex-shrink-0">{fmt(v.amount)}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          {/* Top items */}
          <Card className="rounded-2xl">
            <CardHeader className="px-4 pt-4 pb-2">
              <CardTitle className="text-base flex items-center gap-2"><Package className="h-4 w-4 text-primary" /> Top Items</CardTitle>
            </CardHeader>
            <CardContent className="px-4 pb-4 space-y-3">
              {itemData.length === 0 ? <p className="text-sm text-muted-foreground">No data</p> : itemData.map((item, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center flex-shrink-0">{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold truncate">{item.name}</p>
                    <p className="text-xs text-muted-foreground">{item.count}× purchased</p>
                  </div>
                  <span className="text-sm font-bold flex-shrink-0">{fmt(item.totalSpend)}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          {/* Spend by category — horizontal bar chart */}
          {categoryData.length > 0 && (
            <Card className="rounded-2xl">
              <CardHeader className="px-4 pt-4 pb-2">
                <CardTitle className="text-base">Spend by Category</CardTitle>
              </CardHeader>
              <CardContent className="px-2 pb-4">
                <div style={{ width: '100%', height: Math.max(180, categoryData.length * 36) }}>
                  <ResponsiveContainer>
                    <BarChart data={categoryData} layout="vertical" margin={{ top: 0, right: 40, left: 0, bottom: 0 }}>
                      <XAxis type="number" tickFormatter={v => v >= 1000 ? `${(v / 1000).toFixed(0)}k` : String(v)} tick={{ fontSize: 10 }} />
                      <YAxis type="category" dataKey="name" tick={{ fontSize: 11 }} width={90} />
                      <Tooltip formatter={(v: number) => fmt(v)} contentStyle={{ background: 'hsl(var(--background))', border: '1px solid hsl(var(--border))', borderRadius: 12, fontSize: 12 }} />
                      <Bar dataKey="amount" fill="hsl(var(--primary))" radius={[0, 6, 6, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}
    </div>
  );
};
